### ISSUE TITLE
Uncaught ReferenceError: Price is not defined (pricing.js)

### ISSUE THREAD

**Issue by quantverse** [oanda/v20-javascript#7]
Hello,

the library crashes when attempting to stream prices:

```
Uncaught ReferenceError: Price is not defined
      at /home/xxx/yyy/zzz/node_modules/@oanda/v20/pricing.js:658:44
      at chunks.forEach.chunk (node_modules/@oanda/v20/context.js:137:33)
      at Array.forEach (<anonymous>)
      at IncomingMessage.response.on.d (node_modules/@oanda/v20/context.js:134:32)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at IncomingMessage.Readable.push (_stream_readable.js:208:10)
      at HTTPParser.parserOnBody (_http_common.js:139:22)
      at TLSSocket.socketOnData (_http_client.js:440:20)
      at addChunk (_stream_readable.js:263:12)
      at readableAddChunk (_stream_readable.js:250:11)
      at TLSSocket.Readable.push (_stream_readable.js:208:10)
      at TLSWrap.onread (net.js:607:20)
```

it is apparently missing Price object import, for instance by adding a line:

```javascript
var Price = require('./pricing_common').Price;
```

**Comment by Patafix** [comment]
Same here

**Comment by lukzard** [comment]
change line 658 in pricing.js with

`
streamChunkHandler(new ClientPrice(msg));
`
